apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: guardyn-poc
servers: 3
agents: 2
kubeAPI:
  host: "127.0.0.1"
  hostPort: "6443"
image: rancher/k3s:v1.31.5-k3s1
options:
  k3s:
    extraArgs:
      - arg: "--disable=traefik"
        nodeFilters:
          - server:*
      - arg: "--tls-san=guardyn.local"
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
  runtime:
    gpuRequest: ""
registries:
  create:
    name: guardyn-registry
    host: 0.0.0.0
    hostPort: "5000"
  config: |-
    mirrors:
      "guardyn-registry:5000":
        endpoint:
          - "http://guardyn-registry:5000"
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
  - port: 4222:4222
    nodeFilters:
      - agent:0
  - port: 4223:4223
    nodeFilters:
      - agent:1
