apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base/namespaces
  - ../../base/cert-manager
  - ../../base/cilium
  - ../../base/tikv
  - ../../base/scylladb
  - ../../base/envoy
  - ../../base/minio
  - ../../base/apps
resources:
  - ../../base/monitoring

# Development optimizations - reduce resource usage
patchesStrategicMerge:
  # Reduce all services to 1 replica for local development
  - dev-replicas-patch.yaml
  # Reduce ScyllaDB to 1 node for local development
  - scylla-dev-patch.yaml
