apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base/namespaces
  - ../../base/cert-manager
  - ../../base/cilium
  - ../../base/tikv
  - ../../base/scylladb
  - ../../base/envoy
resources:
  - ../../base/monitoring
