---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: data

resources:
- pd-service.yaml
- pd-statefulset.yaml
- tikv-service.yaml
- tikv-statefulset.yaml

commonLabels:
  guardyn.io/component: tikv
  guardyn.io/stage: poc
