nats:
  image: nats:2.10.9-alpine
  jetstream:
    enabled: true
    fileStore:
      size: 10Gi
      storageClassName: local-path
    memStore:
      enabled: true
      size: 1Gi
  replicaCount: 1
  tls:
    enabled: false
    allowNonTLS: true

config:
  jetstream:
    enabled: true
    storeDir: /data
    maxFileStore: 10GB
    maxMemoryStore: 1GB

cluster:
  enabled: false
  replicas: 1

gateway:
  enabled: false

exporter:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: observability

container:
  image:
    repository: nats
    tag: 2.10.9-alpine
