apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - backend-secrets.yaml
  - auth-service.yaml
  - messaging-service.yaml
  - presence-service.yaml
  - media-service.yaml
  - notification-service.yaml
