operatorNamespace: data
operatorDeployment:
  create: true
clusterCreate:
  create: true
  name: guardyn-fdb
  processes:
    storage:
      count: 3
    stateless:
      count: 3
  databaseConfiguration:
    redundancy_mode: triple
    storage_engine: ssd
